  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check project structure
        run: |
          pwd
          ls -la
          echo "Checking app folder..."
          ls -la app
          echo "Checking tests folder..."
          ls -la tests

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -c "import sys; print(sys.path)"
          python -c "import app; print(app.__file__)"
          python -m pytest --cov=app --cov-report=term-missing --cov-fail-under=85